"""R2-1 — the one written-down statement of what each school profile may reach.

Before this file, nobody's access was written down anywhere. It was granted by
SUBTRACTION: "management" meant *everything not tagged finance*, computed in
`frontend/src/lib/toolPermissions.js` and again at the bottom of
`backend/ai/tool_functions_v2.py`. Two consequences followed from that, and both were
observed on the live platform on 2026-08-10.

First, nothing stated what anyone was *supposed* to have, so nothing could be checked.
The management head could read every teacher's salary, see the school's fee totals,
open and close the accounting posting lock and run the year-end promotion, and no
document said that was wrong.

Second, and worse, subtraction leaks forever. Every screen and every tool built next
month lands in the management head's hands by default, silently, because it was not
tagged finance. Nobody would notice.

This module replaces subtraction with a grant table. It is **default deny**: a screen
or a domain that is not named here is refused. Adding a screen therefore requires
somebody to decide who owns it, which is the entire point.

    THIS FILE IS THE SOURCE OF TRUTH.

`frontend/src/lib/profileMatrix.generated.js` is a mirror of it, generated by
`scripts/generate_profile_matrix.py` and checked in so that Jest and Vite never have to
learn to run Python. `tests/backend/unit/test_profile_matrix_drift.py` fails if the two
drift apart. The checked-in mirror is a convenience; the drift test is the point.

Regenerate after editing:

    backend/.venv/Scripts/python.exe scripts/generate_profile_matrix.py

--------------------------------------------------------------------------------
The nine profiles
--------------------------------------------------------------------------------

`middleware/auth.py` recognises eight admin sub-categories plus the school's owner.
All nine are defined here on purpose. A matrix naming only the four profiles in
Release 2 would have silently stripped receptionist, IT, maintenance and support staff
on the day it was switched on, and the four-profile proof step would not have caught it.

Four are LIVE (people use them or are about to). Five are DORMANT: defined now, so
they cannot drift, but not switched on until their own release. Defining is not
switching on. **The five dormant profiles have zero write tools today and Release 2
must not be what gives them any.**

The five dormant definitions record what each profile reaches TODAY. They are the
observed status quo, not a proposal. The nine questions that would turn them into a
decision are with the school's owner in
`_bmad-output/planning-artifacts/staff-profiles-draft-for-aman-2026-08-10.md` and are
unanswered, so nothing here guesses at his answers.
"""

from __future__ import annotations

from typing import Any, Dict, FrozenSet

# ── Access domains ───────────────────────────────────────────────────────────
#
# Every entry in TOOL_REGISTRY carries an `access_domain`. These are the values a
# profile may be granted. `leadership` is the private surface: the action log, the
# AI's own health and reasoning, and the school's governance reports.
FINANCE = "finance"
NON_FINANCE = "non_finance"
SHARED = "shared"
LEADERSHIP = "leadership"

# Sentinel for the two leadership profiles, which hold the complete surface. Spelled
# as a constant rather than as a bare "*" string so that a screen id can never collide
# with it by accident.
ALL_SCREENS = "__all_screens__"


def _screens(*ids: str) -> FrozenSet[str]:
    return frozenset(ids)


PROFILE_MATRIX: Dict[str, Dict[str, Any]] = {
    # ── LIVE ────────────────────────────────────────────────────────────────
    "owner": {
        "person": "Aman Litt",
        "title": "Owner",
        "status": "live",
        "screens": ALL_SCREENS,
        "tool_domains": frozenset({FINANCE, NON_FINANCE, SHARED, LEADERSHIP}),
        "may_write": True,
        "may_delete_people": True,
        "notes": (
            "The school's proprietor. Holds everything, including the tools marked "
            "owner-only in the registry: the branch records, the school settings and "
            "the year-end promotion. Nobody else reaches those, not even the "
            "principal — see R2-3."
        ),
    },
    "principal": {
        "person": "Adesh Singh",
        "title": "Principal",
        "status": "live",
        "screens": ALL_SCREENS,
        "tool_domains": frozenset({FINANCE, NON_FINANCE, SHARED, LEADERSHIP}),
        "may_write": True,
        "may_delete_people": True,
        "notes": (
            "Stands directly below the owner in the school's own hierarchy "
            "(Aman > Adesh > Sonu > Lalit) and holds the same school-management "
            "surface. He sees every salary, by decision of 2026-08-10. The tools the "
            "registry marks owner-only are the one exception."
        ),
    },
    "accountant": {
        "person": "Sonu Ruhal",
        "title": "Accountant head",
        "status": "live",
        "screens": _screens(
            # Fee and money work: his whole job.
            "finance-commercial-hub",
            "fee-collection",
            "fee-sync",
            "fee-tracker",
            "smart-fee-defaulter",
            "financial-reports",
            "accounting-periods",
            "payroll-manager",
            "expense-tracker",
            "commercial-operations",
            # The student record, because a fee belongs to a child. `data-import` is
            # shared with every authority profile, but each writes only its OWN
            # columns; the narrowing happens on the server in
            # `data_import_service.IMPORT_FIELD_SCOPES`, never by hiding the screen,
            # which would only tell him the feature does not exist.
            "school-database-hub",
            "student-database",
            "data-import",
        ),
        "tool_domains": frozenset({FINANCE, SHARED}),
        "may_write": True,
        "may_delete_people": False,
        "notes": (
            "Finance plus the lookups finance needs. Attendance and leave read-only, "
            "the full directory plus his own columns, vendor records in full, and "
            "transport in full until Release 3 — those widenings are R2-5 and are not "
            "in this table yet. He may create students. He creates certificates and "
            "waits for approval rather than issuing them."
        ),
    },
    "management": {
        "person": "Lalit Thomas",
        "title": "Management, day-to-day data",
        "status": "live",
        "screens": _screens(
            # Overview, but see R2-2: the money tiles on School Pulse and Smart Alerts
            # are still there and must come off. Offering the screen is right; showing
            # him rupees on it is not.
            "overview-hub",
            "school-pulse",
            "principal-daily",
            "attendance-overview",
            "smart-alerts",
            # The student and staff record. This is the bulk of his job.
            "school-database-hub",
            "student-database",
            "staff-tracker",
            "data-import",
            "document-scanner",
            "certificate-generator",
            "id-card-generator",
            # Admissions and talking to families.
            "admissions-communication-hub",
            "admission-funnel",
            "enquiry-register",
            "circular-sender",
            "announcement-broadcaster",
            "parent-message",
            "student-transfer",
            "student-leave-manager",
            # Academics.
            "academics-activities-hub",
            "academic-structure",
            "timetable-builder",
            "exam-manager",
            "quiz-manager",
            "school-activities",
            "attendance-recorder",
            # People operations.
            "people-operations-hub",
            "staff-attendance-tracker",
            "staff-performance",
            "staff-leave-manager",
            "attendance-alerts",
            # Campus and library.
            "campus-library-hub",
            "library-circulation",
            "resource-calendar",
            "asset-tracker",
            "asset-custody",
            "procurement-inventory",
            "facility-requests",
            "maintenance-schedule",
            "vendor-log",
            "raise-maintenance",
            # Transport. Decision 2 hands transport to the accountant head until
            # Release 3 and takes it off Lalit; that is R2-5, not this refactor.
            "transport-hub",
            "transport-manager",
            "transport-optimisation",
            # Reporting and the odds and ends.
            "custom-report-builder",
            "board-report",
            "automated-report",
            "incident-tracker",
            "query-section",
            "custom-form-builder",
            "tech-issues",
            # NOT 'school-settings'. He was offered it until R2-1 and it is a dead
            # button: the screen is backed by `update_school_settings`, which the
            # registry marks owner-only and which R2-3 now refuses him. Offering a
            # button that answers "no" is worse than not offering it.
            #
            # NOT the leadership-private screens: 'audit-log', 'what-ive-learned',
            # 'conversation-trace', 'ai-health-report', 'governance-ai-hub'.
            #
            # NOT any finance screen. He never sees a rupee figure anywhere
            # (decision 1). What he gets instead is a paid-or-unpaid flag, which is
            # R2-2.
        ),
        "tool_domains": frozenset({NON_FINANCE, SHARED}),
        "may_write": True,
        "may_delete_people": False,
        "notes": (
            "Everything that is not money and not leadership-private. He may add and "
            "edit students and staff; he may NOT delete either, and he may not create "
            "or reset any login (decision 4, enforced in R2-4). He creates "
            "certificates and waits for approval."
        ),
    },
    # ── DORMANT ─────────────────────────────────────────────────────────────
    # Defined so they cannot drift. Each records what the profile reaches today.
    # None of them has a single write tool, and Release 2 must not be what changes
    # that. Switching each on is its own release.
    "transport_head": {
        "person": "Chaman Singh",
        "title": "Transport head",
        "status": "dormant",
        "screens": _screens(
            "student-database",
            "transport-manager",
            "transport-optimisation",
            "asset-tracker",
            "custom-form-builder",
            "raise-maintenance",
        ),
        "tool_domains": frozenset(),
        "may_write": False,
        "may_delete_people": False,
        "notes": (
            "Built now, switched on in Release 3 (decision 3). He exists in the staff "
            "records already and has no login."
        ),
    },
    "receptionist": {
        "person": None,
        "title": "Front desk",
        "status": "dormant",
        "screens": _screens(
            "student-database",
            "enquiry-register",
            "commercial-operations",
            "parent-message",
            "student-transfer",
            "asset-tracker",
            "incident-tracker",
            "raise-maintenance",
            "custom-form-builder",
        ),
        "tool_domains": frozenset(),
        "may_write": False,
        "may_delete_people": False,
        "notes": (
            "'id-card-generator' is deliberately absent (D-49): the server refuses a "
            "receptionist, so offering the button only produced a refusal when it was "
            "pressed."
        ),
    },
    "it_tech": {
        "person": None,
        "title": "IT and technical",
        "status": "dormant",
        "screens": _screens(
            "tech-issues",
            "raise-maintenance",
            "custom-form-builder",
            "query-section",
        ),
        "tool_domains": frozenset(),
        "may_write": False,
        "may_delete_people": False,
        "notes": "Awaiting the school owner's answers.",
    },
    "maintenance": {
        "person": None,
        "title": "Maintenance",
        "status": "dormant",
        "screens": _screens(
            "maintenance-schedule",
            "vendor-log",
            "raise-maintenance",
        ),
        "tool_domains": frozenset(),
        "may_write": False,
        "may_delete_people": False,
        "notes": "Awaiting the school owner's answers.",
    },
    "support_staff": {
        "person": None,
        "title": "Support staff",
        "status": "dormant",
        "screens": _screens(
            # Deliberately the narrowest useful set. Until R2-1 this profile had NO
            # list of its own anywhere, so it fell through to most of the admin menu —
            # the single widest unintended grant on the platform, and pure subtraction
            # in its purest form. Closing it properly is R2-6; this entry stops it
            # widening any further in the meantime.
            "raise-maintenance",
            "custom-form-builder",
        ),
        "tool_domains": frozenset(),
        "may_write": False,
        "may_delete_people": False,
        "notes": (
            "Had no entry at all before R2-1 and therefore fell through to the whole "
            "generic admin menu. R2-6 settles what this profile should actually hold; "
            "until then it is deny-by-default with the two screens any employee needs."
        ),
    },
}

LIVE_PROFILES = tuple(
    name for name, entry in PROFILE_MATRIX.items() if entry["status"] == "live"
)
DORMANT_PROFILES = tuple(
    name for name, entry in PROFILE_MATRIX.items() if entry["status"] == "dormant"
)


def user_from_actor(actor_ctx: Any) -> Dict[str, Any]:
    """An ActorContext in the shape the functions below read.

    Services carry an `ActorContext`; routes carry the dict that came out of the JWT.
    Both name the same two things, so rather than teach every caller which shape it is
    holding, this converts the one into the other in a single place.
    """
    return {
        "role": getattr(actor_ctx, "role", None),
        "sub_category": getattr(actor_ctx, "sub_category", None),
        "id": getattr(actor_ctx, "user_id", None),
    }


def profile_of(user: Dict[str, Any]) -> str:
    """Which matrix row governs this user, or "" if none does.

    The school's owner carries `role="owner"`; everyone else in this table is an
    `admin` distinguished by `sub_category`. Teachers, students and guardians are not
    in this table at all and keep ordinary registry role semantics.
    """
    user = user or {}
    if user.get("role") == "owner":
        return "owner"
    if user.get("role") != "admin":
        return ""
    sub_category = user.get("sub_category")
    return sub_category if sub_category in PROFILE_MATRIX else ""


def may_open_screen(user: Dict[str, Any], screen_id: str) -> bool:
    """Default deny. An unknown profile or an unnamed screen is refused."""
    profile = profile_of(user)
    if not profile:
        return False
    screens = PROFILE_MATRIX[profile]["screens"]
    if screens == ALL_SCREENS:
        return True
    return screen_id in screens


def granted_domains(user: Dict[str, Any]) -> FrozenSet[str]:
    """The Flo access domains this user's profile holds. Empty means none."""
    profile = profile_of(user)
    if not profile:
        return frozenset()
    return PROFILE_MATRIX[profile]["tool_domains"]


def may_write(user: Dict[str, Any]) -> bool:
    profile = profile_of(user)
    if not profile:
        return False
    return bool(PROFILE_MATRIX[profile]["may_write"])


def may_delete_people(user: Dict[str, Any]) -> bool:
    """May this profile take a student or a colleague off the roll?

    R2-4 / decision 4, 2026-08-10: the management head may add and edit people, and
    may NOT delete them. Until now `DELETE /api/students/{id}` and
    `DELETE /api/staff/{id}` asked only whether the caller's role was owner or admin,
    which is every admin desk in the school.

    Taking someone off the roll is recoverable — it records that they have left and
    `set_enrolment_state` puts them back — but it removes a child from the school's
    working roll, and that is a decision for the two people who run the school.
    """
    profile = profile_of(user)
    if not profile:
        return False
    return bool(PROFILE_MATRIX[profile]["may_delete_people"])
